### PR TITLE
Update intel_instructions.md

### PR DESCRIPTION
**Pull request by vihanga-w**
Updated intel instructions. The command `brew services start dbus` does not work for all users.

### CODE REVIEW

**Comment by algertc** [comment]
What system are you on? I have tried so many different fixes for this issue and none have worked. On most intel macs, d-bus still does not work. It is the old name. More info in issue #5

**Comment by vihanga-w** [comment]
hi, i'm on a macbook air 2019 with intel i5. dbus started when i ran the command with d-bus.

**Comment by vihanga-w** [comment]
macos ventura 13.1

**Comment by vihanga-w** [comment]
when i ran the command it shows a warning saying it is deprecated and then it successfully starts "dbus"

**Comment by algertc** [comment]
Thank you for bringing this up. I changed the language slightly as results vary by system. Merging now...

**Pull request merged**
